language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
cache: pip

env:
  - TOX_ENV=dj1.10
  - TOX_ENV=dj1.11
  - TOX_ENV=coverage
  #- TOX_ENV=pep8

before_install:
  - pip install tox
  - pip install codecov
script:
  - tox -e $TOX_ENV
after_success:
  - codecov