language: python
cache: pip

env:
  - TOX_ENV=py27-1.10
  - TOX_ENV=py27-1.11
  - TOX_ENV=py35-1.10
  - TOX_ENV=py35-1.11
  - TOX_ENV=coverage
  #- TOX_ENV=pep8

before_install:
  - pip install tox
  - pip install codecov
script:
  - tox -e $TOX_ENV
after_success:
  - codecov